### ISSUE TITLE
Code formating

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#1]
I saw at [your website](https://blog.serenader.me/javascript-shu-zu-qu-zhong/) that your code is color formated. How is the syntax for this?

**Comment by serenader2014** [comment]
@jwillmer Hello, thank you for your attention for this project.

In this project, I use [prism.js](http://prismjs.com/) to enable the syntax highlighting. Prism.js is easy to use, you don't need to modify any code in the theme. You just need to change the way you write your markdown. 

You just need to specify which language of your code block is, and it's done! For example:

``````
```javascript
Array.prototype.uniq = function () {
    var map = {};
    return this.filter(function (item) {
        if (map[item]) {
            return false;
        } else {
            map[item] = true;
            return true;
        }
    });
};
```


```css
html {
    margin: 0;
    padding: 0;
}
```
``````

As you can see, you just need to add the code block's language to let the prism.js know how to render its syntax.

If you have any further question, please let me know.

**Comment by jwillmer** [comment]
Perfect, I know prism! I tested it even with the prism/GitHub syntax but it does not work for c-sharp. Did you maybe not include all supported languages?

**Comment by serenader2014** [comment]
Yes. I just include HTML/Sass/CSS/Javascript (maybe more) languages. If you want to add C# language syntax highlighting maybe you need to download prism.js again and use [UglifyJS](https://github.com/mishoo/UglifyJS) to create the bundle.js file.

Sorry for the inconvenient. I will update the instruction in the README.md soon.

**Comment by jwillmer** [comment]
Yes, not a problem but maybe update the instructions and specify which features are included and how to use them (link to prism).

**Comment by serenader2014** [comment]
@jwillmer Hey, just want to let you know that I've update the README, check it out.

**Comment by jwillmer** [comment]
I would maybe add an additional screenshot that showcases the code highlighting but not needed - documentation looks good, thx for sharing the theme:+1:

**Comment by GeoffreyVDB** [comment]
> In the decent theme folder, run npm install, and run gulp js.

When i run gulp js, i get the command gulp was not found.
So I install gulp with `npm install gulp`
Running gulp js now give me an error: 
```
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
So, what should I do?

**Comment by jwillmer** [comment]
How about a second issue? This one is at the end of it's purpose ;)

**Comment by serenader2014** [comment]
@jwillmer Which issue?

If you want to translate the theme to Jekyll, just do it.

**Comment by jwillmer** [comment]
@GeoffreyVDB added a new issue in the issue. Just ignore it.
