### ISSUE TITLE
Gallery border does not fit

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#11]
I have encountered a problem with the borders of the gallery. Sometimes (tested with around 880px width) the border does not allign with the image. I think the js that modifies the shadow does not work every time. I compared the css of a case there it fitted and a case the it did not and there is no difference. Disabling and enabling the shadow property resolves the issue.

Maybe it is a rendering problem of chrome but could you look over your js, maybe you can change how the resizing is made - via wrapper class?

![image](https://cloud.githubusercontent.com/assets/1503577/15515218/5c9321fc-21ed-11e6-86fe-f0b671b4c32a.png)

I tested it with different browsers and some have the same problem:
https://www.browserstack.com/screenshots/eef6a6439abb3e70d34a20fda268e2b950685654

**Comment by serenader2014** [comment]
That's wired. I've seen this issue couple times. I'm not using JS to apply the shadow, css instead. So maybe this is chrome's issue.

I've improved the style in this part, hope that will fix the problem.
