### ISSUE TITLE
Pimp the author profile page

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#15]
I propose the following changes to the author page:

```
    $(window).scroll(function () {
        var scrolledY = 50 + $(window).scrollTop() / 5;
        if (scrolledY <= 100) {
            $('.author-cover').css('background-position', '50% ' + ((scrolledY)) + '%');
        }
    });
```

Demo: http://jwillmer.github.io/jekyllDecent/about/

**Comment by serenader2014** [comment]
Worth a try.

**Comment by jwillmer** [comment]
Don't do it. I tried it and I think it does not work together with the rest of the design. I will remove it from my template. Have a look: [jwillmer.de](http://jwillmer.de/about/)
