### ISSUE TITLE
Implement fallback.js

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#17]
Now with 6-7 js files it could be a good idea to implement [fallback.js](http://fallback.io/). You can setup to load the scripts async (not blocking), you can define CDN's and use the local files if the CDN is down. It also seams fairly easy to implement.

[This is the link to the documentation](https://github.com/dolox/fallback/blob/master/README.md)

I also read that you can load css files with this library but you should not do this for important files like your `screen.css` file because some browsers have problems with async loading of css files. But it sill might be an idea for the `prism.css`file

**Comment by serenader2014** [comment]
Well I don't think it's a good idea to implement this feature. It's too much for a blog's theme. Besides, now the script load quite fast.
