### ISSUE TITLE
Go to top button changes

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#18]
How about changing `bottom: 30px` to `top: 30px`?
I tested the current design on a mobile and guess there I try to scroll the page? Exactly over the go-to-top button :-1:

**Comment by serenader2014** [comment]
Actually I think this part was over designed. There is a key called <kbd>Home</kbd> and it does the same function as the Go To Top Button. I want the whole design as simple as possible. So I'm considering remove the button.

**Comment by jwillmer** [comment]
What di you mean with key called `home`?

**Comment by serenader2014** [comment]
I mean the <kbd>Home</kbd> key in your keyboard.

**Comment by jwillmer** [comment]
I don´t know any normal person who use that button or knows what it does. I know the key but it is faster to use the mouse because your hand is already there - scrolling. Another thing is that tablet and phone users don´t have that key. 

You can remove it but I think it is a usability improvement.
