### ISSUE TITLE
Uncaught ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by julianxhokaxhiu** [serenader2014/decent#29]
Hi,

first of all let me thank you for your work. This theme is amazing :) I like it very much.

By using it right now, I saw that when I reload the page by clicking the logo on top-left, something this error appears in Console:

```
Uncaught ReferenceError: ga is not defined
```

And I think it's because on this line ( https://github.com/serenader2014/decent/blob/master/src/script/index.js#L28 ) there's no check if `decentThemeConfig.ga` is defined.

Can you please add it?

Thank you in advance,
Julian

**Comment by serenader2014** [comment]
Thank you for your debugging, I will fix it when I have time.

**Comment by serenader2014** [comment]
fixed in c375cafda9909ec73a8b75d0a0155e88bc213862, feel free to try it.

**Comment by julianxhokaxhiu** [comment]
Thank you very much, tested and it works.
