### ISSUE TITLE
Gulp 'build' task

### ISSUE THREAD

**Issue by julianxhokaxhiu** [serenader2014/decent#30]
Can you please provide a build task inside `Gulpfile.js` so it's easier to recompile without the need of `watch` and `dev` tasks?

Thank you in advance,
Julian

**Comment by serenader2014** [comment]
Added in e1994eca389c3f21c106ac660eab0fe4be388415 :)

**Comment by julianxhokaxhiu** [comment]
Very fast! Wow :D Thank you!
