### ISSUE TITLE
Changing the Blog Title font/replace by image

### ISSUE THREAD

**Issue by haideralipunjabi** [serenader2014/decent#31]
Is it possible to change the font of the title, or replace it entirely with an image?

**Comment by serenader2014** [comment]
Of course, you can. The theme is using Google Font for custom font styling, and currently the font for the blog title is _Mrs Saint Delafield_, defined in 
[https://github.com/serenader2014/decent/blob/master/src/style/main.scss#L54](https://github.com/serenader2014/decent/blob/master/src/style/main.scss#L54), 
you're free to change to the font you like, just remember to change the Google Font css file's href: [https://github.com/serenader2014/decent/blob/master/default.hbs#L19](https://github.com/serenader2014/decent/blob/master/default.hbs#L19)
