### ISSUE TITLE
Adding more language support to syntax highlighting

### ISSUE THREAD

**Issue by ghost** [serenader2014/decent#7]
Hello,

> In the decent theme folder, run `npm install`, and run `gulp js`.

But I get a command not found for gulp, so I install gulp by running `npm install gulp`.
Running `gulp js` now gives me the following error:

```
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/var/www/ghost/content/themes/decent-v1.1.1/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

So what do I do now? I'm kind of a noob at this, apologies if this issue can be trivially solved

**Comment by serenader2014** [comment]
Hi Geoffrey.

You need to install Gulp first before running `gulp js`. In most case you can run `npm install -g gulp` to install it(it will require root permission if you use Linux/Mac system).

And from your error logs, I guess you haven't install `node-sass` successfully. Try running `npm install node-sass` again.

BTW, I will include more languages in the next release. Which language do you need?

**Comment by ghost** [comment]
Shouldn't `npm install` take care of installing `gulp` and `node-sass`?
I tried running `npm install node-sass` again but still the same error. What should create the vendor directory in node-sass?
Could it be that these errors are due to an older linux distro? I'm running Ubuntu 14.04 with npm v2.15.1, I'll try to install it on 16.04
Edit: seems that the npm package in the repository is outdated, however updating it and rerunning the steps still failed for me

**Comment by serenader2014** [comment]
The `vendor` folder is used to place the binary file that will be used by `node-sass` .

Node-sass will try to download the binary from Github in the postinstall stage. So maybe the download isn't success, and perhaps this is the reason you get these errors.

**Comment by serenader2014** [comment]
I think it's not your linux version's problem. The vendor folder is used to place the Node-sass's binary file. If the binary file is missing, it will try to build from source file as fallback. If the build failed, your Node-sass won't work.

The problem is, Node-sass will try to download the binary from Github(see https://github.com/sass/node-sass/blob/master/package.json#L31), and maybe your download isn't success, and build from source file failed, so the problem occur.

You can try to reinstall the Node-sass package behind a proxy.

**Comment by serenader2014** [comment]
Just want to let you know that I've updated the theme to v1.1.2, and it comes with a lot languages syntax highlighting support. Just checkout the README to see what language has included.

**Comment by ghost** [comment]
Very nice thank you, what does this mean in terms of performance? Is it noticeable?

**Comment by serenader2014** [comment]
The size of the bundle file is increases about 50kb after gzip, so I think it's acceptable.
